import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { UserRound, PackageCheck, MapPin, ArrowLeft } from "lucide-react";

export default function Account() {
  const { user, loading, logout } = useAuth();
  if (loading) return <div className="min-h-screen bg-[#f6f7fb] p-10 text-slate-500">Loading account…</div>;
  if (!user) return <div className="flex min-h-screen items-center justify-center bg-[#0b1736] p-5 text-white"><div className="max-w-md rounded-3xl bg-white/10 p-8 text-center"><UserRound className="mx-auto mb-5 text-cyan-200" size={40}/><h1 className="text-3xl font-semibold">Your Olucha account</h1><p className="mt-3 leading-7 text-white/65">Sign in to view your profile, orders, delivery details, and future order status updates.</p><button onClick={() => startLogin()} className="mt-7 rounded-full bg-[#f7b32b] px-6 py-3 text-sm font-bold text-[#0b1736]">Sign in</button></div></div>;
  return <div className="min-h-screen bg-[#f6f7fb] text-[#14213d]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-cyan-700"><ArrowLeft size={17}/> Back to store</Link><button onClick={() => logout()} className="text-sm font-semibold text-slate-500">Sign out</button></div></header><main className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-700">Customer account</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em] text-[#0b1736]">Welcome back, {user.name || "customer"}.</h1><div className="mt-10 grid gap-5 lg:grid-cols-3"><div className="rounded-3xl bg-white p-6 shadow-sm"><UserRound className="text-cyan-700" size={22}/><h2 className="mt-6 font-semibold">Profile details</h2><p className="mt-2 text-sm text-slate-500">{user.email || "Email not supplied"}</p><p className="mt-1 text-sm text-slate-500">Update your contact details during checkout.</p></div><div className="rounded-3xl bg-white p-6 shadow-sm"><PackageCheck className="text-cyan-700" size={22}/><h2 className="mt-6 font-semibold">Order history</h2><p className="mt-2 text-sm text-slate-500">Your completed orders will appear here after checkout is connected.</p><span className="mt-6 inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700">No orders yet</span></div><div className="rounded-3xl bg-white p-6 shadow-sm"><MapPin className="text-cyan-700" size={22}/><h2 className="mt-6 font-semibold">Delivery tracking</h2><p className="mt-2 text-sm text-slate-500">Track processing, dispatch, and delivery status from one place.</p><span className="mt-6 inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500">Ready for first order</span></div></div></main></div>;
}
