import { ArrowLeft, ArrowRight, Newspaper } from "lucide-react";
import { Link, useRoute } from "wouter";

const articles: Record<string, { tag: string; title: string; body: string; paragraphs: string[] }> = {
  "buying-electronics-online": { tag: "Buying guide", title: "What to check before buying electronics online", body: "A practical guide to choosing useful devices, confirming specifications, and ordering with confidence.", paragraphs: ["Start with the job the product needs to do. Clear product descriptions help you compare practical features rather than choosing on appearance alone.", "Next, check the quantity, unit, delivery location, and any support included with the order. Olucha keeps these details visible so customers can make informed choices.", "Finally, review your cart and delivery details carefully before payment. A dependable buying experience combines useful products with clear service at every step."] },
  "better-everyday-products": { tag: "Store note", title: "Choosing better products for everyday use", body: "How clear product information and dependable service shape a better online shopping experience.", paragraphs: ["Quality is more than a label. It includes a product that fits the customer's needs, a price that is easy to understand, and support when questions come up.", "Our catalogue brings together everyday electronics, fashion, and agro products so customers can shop from a focused selection with confidence.", "We continue to improve the store around clear information, responsible fulfilment, and long-term customer relationships."] },
  "three-store-categories": { tag: "Product focus", title: "Everyday essentials across three categories", body: "Explore how electronics, fashion, and agro products come together in one trusted store.", paragraphs: ["Electronics lead the store with practical devices and power accessories for homes, travel, and small businesses.", "Fashion adds curated apparel and accessories for personal wardrobes, gifting, and retail buyers.", "Agro products complete the range with carefully sourced produce for households, retailers, and food businesses."] },
};

export default function NewsArticle() {
  const [, params] = useRoute("/news/:slug");
  const article = articles[params?.slug || ""];
  if (!article) return <div className="min-h-screen bg-[#f6f7fb] p-10"><Link href="/news" className="font-bold text-cyan-700">← Back to news</Link><h1 className="mt-16 text-3xl font-semibold text-[#0b1736]">Article not found</h1></div>;
  return <div className="min-h-screen bg-[#f6f7fb] text-[#14213d]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link href="/news" className="inline-flex items-center gap-2 text-sm font-bold text-cyan-700"><ArrowLeft size={17}/> All news</Link><Newspaper size={20} className="text-[#0b1736]"/></div></header><main className="mx-auto max-w-3xl px-5 py-14 lg:py-20"><p className="eyebrow">{article.tag}</p><h1 className="mt-3 text-4xl font-semibold leading-tight tracking-[-.05em] text-[#0b1736] sm:text-6xl">{article.title}</h1><p className="mt-6 text-xl leading-8 text-slate-600">{article.body}</p><div className="mt-12 space-y-7 rounded-[2rem] bg-white p-7 shadow-sm sm:p-10">{article.paragraphs.map((paragraph) => <p key={paragraph} className="text-lg leading-8 text-slate-600">{paragraph}</p>)}<Link href="/shop" className="inline-flex items-center gap-2 rounded-full bg-[#f7b32b] px-5 py-3 text-sm font-bold text-[#0b1736]">Shop the store <ArrowRight size={15}/></Link></div></main></div>;
}
